# Copyright (c) 2001-2018 by SAP SE, Walldorf, Germany.
# All rights reserved. Confidential and proprietary.

# ansible 2.4
---
  - name: Setup SapMachine Linux PPC64LE Slave
    hosts: SapMachineSlave-Linux-ppc64le
    gather_facts: False
    pre_tasks:
      - name: 'install python2'
        raw: sudo apt-get update && sudo apt-get -qq -y --no-install-recommends install python
    vars:
      slave_jar_version: 3.21
      jenkins_master_url: https://ci.sapmachine.io/computer/agent-linux-ppc64le-1/slave-agent.jnlp
      jenkins_slave_name: agent-linux-ppc64le-1

    tasks:

      - name: install apt-transport-https
        apt:
          name: apt-transport-https
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.apt-transport-https

      - name: add docker apt key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
        become: yes
        tags:
          - packages.docker_key

      - name: add docker repository
        apt_repository:
         repo: deb [arch=ppc64el] https://download.docker.com/linux/ubuntu xenial stable
         state: present
        become: yes
        tags:
          - packages.docker_repository

      # install docker, docker-compose, OpenJDK 8 JRE
      - name: install docker-ce
        apt:
          name: docker-ce
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.docker-ce

      - name: install OpenJDK 8 JRE
        apt:
         name: openjdk-8-jre
         state: latest
         install_recommends: no
        become: yes
        tags:
          - packages.openjdk

      # create jenkins group and user
      # used for running the jenkins slave
      - name: create jenkins group
        group:
          name: jenkins
          state: present
        become: yes
        tags:
          - groups.create_jenkins

      - name: create jenkins user
        user:
          name: jenkins
          comment: "Jenkins user"
          groups: jenkins, docker
        become: yes
        tags:
          - users.create_jenkins

      # create the jenkins slave home directory
      - name: create Jenkins Slave home directory
        file:
          path: /home/jenkins/slave-home
          state: directory
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave.create_home

      # download the jenkins slave jar file
      - name: download Jenkins Slave jar
        get_url:
          url: "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/{{ slave_jar_version }}/remoting-{{ slave_jar_version }}.jar"
          dest: /home/jenkins/slave.jar
          force: yes
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave.download_slave_jar

      # copy the script file to start the jenkins slave
      - name: copy Jenkins Slave files
        synchronize:
          src: ../ci-slave-local/start-slave.sh
          dest: /home/jenkins/start-slave.sh
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave.copy_files

      # enable Docker IPv6
      - name: install Docker Daemon configuration
        copy:
          src: daemon.json
          dest: /etc/docker/daemon.json
          owner: root
          group: root
          mode: 0644
        become: yes
        tags:
          - docker.config_install

      - name: reload the Docker Daemon configuration
        systemd: state=restarted name=docker
        become: yes
        tags:
          - docker.config_reload

      # stop all running java processes (jenkins slave)
      - name: stop all Java processes
        command: killall -9 java
        become: yes
        failed_when: false
        tags:
          - java.kill_all

      # start the jenkins slave
      - name: start Jenkins Slave
        command: "/home/jenkins/start-slave.sh {{ jenkins_master_url }} {{ jenkins_slave_secret }}"
        args:
          chdir: /home/jenkins
        become: yes
        become_user: jenkins
        tags:
          - jenkins_slave.start
